package com.ronda.saleassist.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * 分类信息：既包括称重类货物的分类，也包括条码类货物的分类（在批量修改条码类单价时会使用）
 *
 * Entity mapped to table "CATEGORY".
 */
public class Category implements Serializable {

    /**
     * id : 100090
     * shopid : 100001
     * notes :
     * status : 1
     * name : 水果4
     */
    private String id;
    private String name;
    private String notes;
    private String shopid;

    public Category() {
    }

    public Category(String id) {
        this.id = id;
    }

    public Category(String id, String name, String notes) {
        this.id = id;
        this.name = name;
        this.notes = notes;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }


    public void setName(String name) {
        this.name = name;
    }

    public String getNotes() {
        return notes;
    }


    public void setNotes(String notes) {
        this.notes = notes;
    }

    public String getShopid() {
        return shopid;
    }

    public void setShopid(String shopid) {
        this.shopid = shopid;
    }


    // 修改货物时LSpinner会使用
    @Override
    public String toString() {
        return name;
    }
}
